name: Deploy to Forpsi and Sync Firestore

on:
  push:
    branches:
      - main

jobs:
  web-deploy-public:
    name: FTP Deploy Public
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/
        local-dir: ./public/

  web-deploy-admin:
    name: FTP Deploy Admin
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /subdoms/admin/
        local-dir: ./admin/

  firestore-sync:
    name: Firestore Sync
    runs-on: ubuntu-latest
    # This ensures it only runs if HTML files in the admin-pages folder are changed
    if: github.event_name == 'push'
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install firebase-admin cheerio

    - name: Run Upload Script
      run: node ./firestore/admin-pages/upload.js
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
